server: 
  port: 9003
spring: 
  application:  
    name: tenpower-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.129:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: WYX*wyx123
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: bofeng
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #使该微服务在上线后能被跨域访问
feign:
  hystrix:
    enabled: true