server:
  port: 12000
spring:
  application:
    name: tenpower-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/naixin023/tenpower-config.git
          username: naixin023         #私有仓库需要
          password: lioukangdi199695  #私有仓库需要
          skip-ssl-validation: true   #github是https连接，需要跳过ssl验证
  rabbitmq:
    host: 192.168.25.129
management: #暴露出发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh